In [1]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder 
from sklearn.model_selection import train_test_split

In [2]:
cus_df = pd.read_csv('cust_satisfaction.csv')
cus_df

,Gender,Customer Type,Type of Travel,Class,satisfaction,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,Male,Loyal Customer,Personal Travel,Eco Plus,neutral or dissatisfied,13,460,5,4,5,25,18.0
1,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied,25,235,1,3,1,1,6.0
2,Female,Loyal Customer,Business travel,Business,satisfied,26,1142,5,4,5,0,0.0
3,Female,Loyal Customer,Business travel,Business,neutral or dissatisfied,25,562,2,3,2,11,9.0
4,Male,Loyal Customer,Business travel,Business,satisfied,61,214,3,4,3,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
103899,Female,disloyal Customer,Business travel,Eco,neutral or dissatisfied,23,192,2,4,2,3,0.0
103900,Male,Loyal Customer,Business travel,Business,satisfied,49,2347,5,5,4,0,0.0
103901,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied,30,1995,4,4,4,7,14.0
103902,Female,disloyal Customer,Business travel,Eco,neutral or dissatisfied,22,1000,1,1,1,0,0.0
103903,Male,Loyal Customer,Business travel,Business,neutral or dissatisfied,27,1723,1,4,1,0,0.0

In [3]:
cus_df.describe()

,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
count,103904.000000,103904.000000,103904.000000,103904.000000,103904.000000,103904.000000,103594.000000
mean,39.379706,1189.448375,3.358158,3.631833,3.286351,14.815618,15.178678
std,15.114964,997.147281,1.332991,1.180903,1.312273,38.230901,38.698682
min,7.000000,31.000000,0.000000,1.000000,0.000000,0.000000,0.000000
25%,27.000000,414.000000,2.000000,3.000000,2.000000,0.000000,0.000000
50%,40.000000,843.000000,4.000000,4.000000,3.000000,0.000000,0.000000
75%,51.000000,1743.000000,4.000000,5.000000,4.000000,12.000000,13.000000
max,85.000000,4983.000000,5.000000,5.000000,5.000000,1592.000000,1584.000000

In [4]:
cus_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103904 entries, 0 to 103903
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Gender                      103904 non-null  object
 1   Customer Type               103904 non-null  object
 2   Type of Travel              103904 non-null  object
 3   Class                       103904 non-null  object
 4   satisfaction                103904 non-null  object
 5   Age                         103904 non-null  int64
 6   Flight Distance             103904 non-null  int64
 7   Inflight entertainment      103904 non-null  int64
 8   Baggage handling            103904 non-null  int64
 9   Cleanliness                 103904 non-null  int64
 10  Departure Delay in Minutes  103904 non-null  int64
 11  Arrival Delay in Minutes    103594 non-null  float64
dtypes: float64(1), int64(6), object(5)
memory usage: 9.5+ MB

In [5]:
cus_df.shape

(103904, 12)

In [6]:
cus_df.isnull().sum()

Gender                          0
Customer Type                   0
Type of Travel                  0
Class                           0
satisfaction                    0
Age                             0
Flight Distance                 0
Inflight entertainment          0
Baggage handling                0
Cleanliness                     0
Departure Delay in Minutes      0
Arrival Delay in Minutes      310
dtype: int64

In [7]:
ncus_df = cus_df.dropna()
ncus_df.shape

(103594, 12)

In [8]:
ndcus_df = ncus_df.drop_duplicates()

In [9]:
ndcus_df.shape

(103422, 12)

In [10]:
ndcus_df.duplicated().sum()

np.int64(0)

In [11]:
ndcus_df['Gender'].unique()

ch = {
    'Male': 0,
    'Female': 1,
}

ndcus_df['Gender'] = ndcus_df['Gender'].map(ch)
ndcus_df

C:\Users\varun\AppData\Local\Temp\ipykernel_13780\3193446882.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ndcus_df['Gender'] = ndcus_df['Gender'].map(ch)

,Gender,Customer Type,Type of Travel,Class,satisfaction,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,0,Loyal Customer,Personal Travel,Eco Plus,neutral or dissatisfied,13,460,5,4,5,25,18.0
1,0,disloyal Customer,Business travel,Business,neutral or dissatisfied,25,235,1,3,1,1,6.0
2,1,Loyal Customer,Business travel,Business,satisfied,26,1142,5,4,5,0,0.0
3,1,Loyal Customer,Business travel,Business,neutral or dissatisfied,25,562,2,3,2,11,9.0
4,0,Loyal Customer,Business travel,Business,satisfied,61,214,3,4,3,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
103899,1,disloyal Customer,Business travel,Eco,neutral or dissatisfied,23,192,2,4,2,3,0.0
103900,0,Loyal Customer,Business travel,Business,satisfied,49,2347,5,5,4,0,0.0
103901,0,disloyal Customer,Business travel,Business,neutral or dissatisfied,30,1995,4,4,4,7,14.0
103902,1,disloyal Customer,Business travel,Eco,neutral or dissatisfied,22,1000,1,1,1,0,0.0
103903,0,Loyal Customer,Business travel,Business,neutral or dissatisfied,27,1723,1,4,1,0,0.0